// ============================================================
// data.js — IELTS 闖關密碼：所有靜態資料
// ============================================================

const FAMILIES = [
    {
        id: 0, icon: '🏛️', name: '制度與政策', en: 'System & Policy',
        keywords: ['government', 'law', 'regulation', 'tax', 'policy', 'fund', 'public', 'reform', 'ban'],
        hypernyms: ['政策制定者', '法規', '公共資金', '公共服務', '獨立監管', '國際合作', '禁令'],
        hyEN: [
            'the government / authorities / policymakers / decision-makers / governments',
            'regulation / legislation / law / policy / restrictions / reform / legalisation',
            'public funds / government budget / subsidies / taxpayer money / grants / funding / donations',
            'public services / healthcare / education / public safety / infrastructure / public institutions',
            'independent oversight / regulators / ethics committees / accountability / transparency',
            'international cooperation / diplomacy / foreign aid / global agreements / wealthy nations',
            'ban / prohibition / restriction / censorship / crackdown'
        ]
    },
    {
        id: 1, icon: '👤', name: '受影響群體', en: 'Affected Groups',
        keywords: ['children', 'young', 'old', 'worker', 'people', 'family', 'student', 'celebrity', 'athlete', 'women'],
        hypernyms: ['年輕人', '勞工', '弱勢族群', '納稅人', '家庭', '名人/運動員', '難民/移民', '女性'],
        hyEN: [
            'young people / teenagers / students / children / learners / minors / graduates / youth / the next generation',
            'workers / employees / professionals / low-skilled workers / workforce',
            'the elderly / low-income families / minorities / the disabled / vulnerable people / single parents',
            'taxpayers / citizens / the public / residents / individuals / society',
            'families / parents / children / guardians / a parent / household',
            'celebrities / athletes / public figures / role models / influencers / sports professionals',
            'refugees / immigrants / migrant workers / asylum seekers / displaced people',
            'women / working mothers / gender equality / female empowerment'
        ]
    },
    {
        id: 2, icon: '💰', name: '經濟與資源', en: 'Economy & Resources',
        keywords: ['money', 'job', 'salary', 'cost', 'expensive', 'economy', 'income', 'debt', 'spend', 'business', 'company'],
        hypernyms: ['經濟活動', '成本', '就業', '消費', '不平等', '債務'],
        hyEN: [
            'economic growth / job creation / revenue / GDP / employment / productivity / industries',
            'cost / budget / investment / funding / expensive / resources / financial support',
            'jobs / employment / careers / workforce / labour / entrepreneurship / startups',
            'spending / consumer / purchases / overconsumption / advertising / luxury',
            'inequality / poverty / wealth gap / class divide / privilege / family wealth',
            'debt / credit / loans / bankruptcy / borrowing / financial literacy'
        ]
    },
    {
        id: 3, icon: '🧠', name: '健康與心理', en: 'Health & Wellbeing',
        keywords: ['health', 'obesity', 'stress', 'mental', 'addiction', 'disease', 'wellbeing', 'exercise'],
        hypernyms: ['心理健康', '身體健康', '成癮', '過勞', '吸菸/菸害', '肥胖'],
        hyEN: [
            'mental health / anxiety / depression / burnout / stress / wellbeing / self-esteem / loneliness / motivation',
            'physical health / disease / life expectancy / exercise / obesity / patients / medical treatment',
            'addiction / dependency / substance abuse / screen addiction',
            'overwork / burnout / exhaustion / work-life imbalance',
            'smoking / tobacco / nicotine / passive smoking / substance use',
            'obesity / junk food / sedentary lifestyle / calorie intake / malnutrition'
        ]
    },
    {
        id: 4, icon: '🌍', name: '環境與永續', en: 'Environment',
        keywords: ['pollution', 'climate', 'environment', 'energy', 'wildlife', 'emission', 'fossil', 'transport', 'conservation'],
        hypernyms: ['碳排放', '生態系統', '再生能源', '資源消耗', '氣候變遷', '食物里程', '公共交通'],
        hyEN: [
            'carbon emissions / greenhouse gases / pollution / CO2 / electric vehicles / EVs',
            'ecosystems / biodiversity / wildlife / natural habitats / conservation / endangered species / extinction',
            'renewable energy / solar / wind / clean energy / nuclear',
            'resource scarcity / waste / deforestation / overconsumption',
            'climate change / global warming / extreme weather',
            'food miles / air freight / transport emissions / supply chain carbon footprint',
            'public transport / cycling / congestion / commuting / infrastructure'
        ]
    },
    {
        id: 5, icon: '📱', name: '科技與數位', en: 'Technology & Digital',
        keywords: ['technology', 'AI', 'internet', 'social media', 'computer', 'phone', 'privacy', 'digital', 'robot', 'innovation'],
        hypernyms: ['AI/自動化', '社群媒體', '隱私', '數位素養', '螢幕成癮'],
        hyEN: [
            'AI / automation / robots / technology / algorithms / machine learning / innovation',
            'social media / platforms / online communities / digital content / influencers / viral content',
            'privacy / data collection / surveillance / personal data / smartphones / devices',
            'digital literacy / media literacy / fact-checking / fake news / misinformation / propaganda',
            'screen time / phone addiction / gaming addiction'
        ]
    },
    {
        id: 6, icon: '🎓', name: '教育與發展', en: 'Education',
        keywords: ['school', 'education', 'exam', 'university', 'teach', 'learn', 'curriculum', 'subject', 'skill', 'homework'],
        hypernyms: ['教育體系', '技能', '考試制度', '教師', '課綱', '幼兒教育', '競爭合作'],
        hyEN: [
            'education system / schools / universities / curricula / higher education',
            'skills / creativity / critical thinking / practical skills / vocational / discipline / effort',
            'exams / grades / academic pressure / standardised testing / homework / assignments',
            'teachers / educators / mentors / tutors',
            'curriculum / subjects / STEM / arts / vocational',
            'childcare / early learning / preschool / kindergarten / nursery',
            'competition / cooperation / teamwork / rivalry / individuality / conformity'
        ]
    },
    {
        id: 7, icon: '⚖️', name: '倫理與自由', en: 'Ethics & Freedom',
        keywords: ['freedom', 'right', 'fair', 'censor', 'culture', 'tradition', 'animal', 'ethic', 'moral', 'crime', 'punishment'],
        hypernyms: ['個人自由', '倫理邊界', '公平', '言論自由', '文化認同', '動物權利', '刑罰/犯罪'],
        hyEN: [
            'personal freedom / autonomy / choice / individual rights',
            'ethical boundaries / moral limits / consent / human dignity / values / accountability',
            'fairness / equality / equity / justice / equal opportunity / social cohesion / inclusion',
            'free speech / censorship / artistic freedom / political criticism',
            'cultural identity / heritage / tradition / indigenous culture',
            'animal rights / animal welfare / ethical treatment / animal testing',
            'punishment / crime / rehabilitation / prison / justice system / offenders'
        ]
    },
    {
        id: 8, icon: '🔄', name: '生活方式與社會變遷', en: 'Lifestyle & Change',
        keywords: ['fashion', 'travel', 'food', 'gift', 'vegetarian', 'study abroad', 'parenthood', 'medicine', 'building', 'language', 'tourism', 'alone', 'urban'],
        hypernyms: ['城市化', '時尚產業', '即時文化', '素食主義', '禮物/人際', '旅行方式', '留學', '晚生育', '替代醫學', '建築安全', '語言學習', '獨居趨勢'],
        hyEN: [
            'urbanisation / overcrowding / cities / population growth / neighbourhoods / rural areas',
            'fast fashion / textile waste / clothing consumption',
            'instant gratification / convenience culture / impatience / instant delivery',
            'vegetarianism / plant-based diet / ethical eating',
            'gift-giving / social customs / community / personal gifts / monetary gifts / relationships',
            'tourism / domestic tourism / independent travel / guided tours / backpacking / visitors',
            'study abroad / international students / overseas education',
            'delayed parenthood / late marriage / fertility decline',
            'alternative medicine / acupuncture / herbal medicine / holistic',
            'building codes / safety standards / housing regulations',
            'bilingual education / immersion / early language learning',
            'living alone / solo living / independence / single-person household'
        ]
    }
];

const ENGINES = [
    { id: 'E1', label: '✅ 改善生活', formula: "{X} makes {people's} life more {adj} because they can {benefit}." },
    { id: 'E2', label: '❌ 造成傷害', formula: "It damages {group's} {aspect} when {cause}, leading to {consequence}." },
    { id: 'E3', label: '❌ 太貴了', formula: 'It is too expensive for {group} when {cost situation}.' },
    { id: 'E4', label: '⏩ 正向預測', formula: 'If {action}, {beneficiary} will {result}.' },
    { id: 'E5', label: '⏩ 負面警告', formula: 'Without {action}, we face {consequence}.' },
    { id: 'E6', label: '👁️ 現象描述', formula: 'We often see {phenomenon} — {context}.' },
    { id: 'E7', label: '👁️ 統計顯示', formula: 'Statistics show {data point} — {implication}.' },
    { id: 'E8', label: '🔧 政府必須', formula: 'The government must {policy action} to {outcome}.' },
    { id: 'E9', label: '🔧 學校應該', formula: 'Schools should teach {skill} so {students} can {application}.' },
    { id: 'E10', label: '🔧 折衷平衡', formula: 'Rather than {A or B}, a balanced approach would be to {middle ground}.' },
    { id: 'E11', label: '🔄 反方觀點', formula: 'The opposing view argues that {counter-argument}, but this overlooks {rebuttal}.' },
    { id: 'E12', label: '📌 具體舉例', formula: 'For instance, in {country/context}, {specific example}, which demonstrates {point}.' }
];

const EXAMS = [
    // === Original Hypernym Template Exams (21) ===
    { id: 1, q: "Teachers should teach students to distinguish right from wrong vs focus solely on academics.", topic: "Teachers: ethics vs academics", fam: [6, 7], eng: ['E2', 'E9', 'E10'] },
    { id: 2, q: "Children should have freedom to make mistakes vs adults should prevent them.", topic: "Children making mistakes", fam: [1, 7], eng: ['E1', 'E2', 'E10'] },
    { id: 7, q: "People should choose jobs based on salary rather than personal interest.", topic: "Job choice based on salary", fam: [2, 1], eng: ['E1', 'E2', 'E10'] },
    { id: 8, q: "Money is the best gift vs personal gifts are more meaningful.", topic: "Money vs personal gifts", fam: [8, 7], eng: ['E1', 'E2', 'E10'] },
    { id: 10, q: "Every country should use its own resources to live on rather than importing from other countries.", topic: "Local resources; environment", fam: [4, 0], eng: ['E1', 'E5', 'E8'] },
    { id: 13, q: "The fashion industry has a negative effect on the environment.", topic: "Fashion industry; environment", fam: [8, 4], eng: ['E2', 'E5', 'E7'] },
    { id: 15, q: "It is acceptable to use animals for food and medical research.", topic: "Using animals for food/medicine", fam: [7], eng: ['E2', 'E5', 'E10'] },
    { id: 17, q: "People today want everything immediately — instant culture.", topic: "Instant gratification culture", fam: [8, 5], eng: ['E2', 'E6', 'E10'] },
    { id: 19, q: "Sports professionals earn too much money compared to other workers.", topic: "Sports stars' salary", fam: [1, 7, 2], eng: ['E2', 'E3', 'E10'] },
    { id: 21, q: "Celebrities have a right to privacy vs media should report on them freely.", topic: "Celebrity privacy; media", fam: [1, 7, 5], eng: ['E2', 'E6', 'E10'] },
    { id: 25, q: "The government should spend more money on healthcare than on other areas.", topic: "Government healthcare spending", fam: [0, 3], eng: ['E3', 'E8', 'E10'] },
    { id: 31, q: "Many animal species are becoming extinct. What causes this and what solutions are there?", topic: "Animal extinction", fam: [4, 7], eng: ['E2', 'E5', 'E8'] },
    { id: 35, q: "Countries should reduce their use of fossil fuels such as oil and gas.", topic: "Fossil fuels reduction", fam: [4, 0], eng: ['E5', 'E7', 'E8'] },
    { id: 40, q: "Young people should be taught how to manage money wisely.", topic: "Youth money management", fam: [2, 6], eng: ['E2', 'E6', 'E9'] },
    { id: 42, q: "The media has too much influence on people's opinions.", topic: "Media controls opinions", fam: [5, 7], eng: ['E2', 'E5', 'E8'] },
    { id: 50, q: "Some people think governments should spend money on space exploration rather than on basic needs.", topic: "Space exploration vs basics", fam: [2, 0], eng: ['E3', 'E7', 'E10'] },
    { id: 55, q: "Testing and exams put too much pressure on students.", topic: "Testing pressure", fam: [6, 3], eng: ['E2', 'E6', 'E9'] },
    { id: 58, q: "Vegetarianism is better for health and the environment.", topic: "Vegetarianism; health/ethics", fam: [8, 7, 3], eng: ['E1', 'E2', 'E7'] },
    { id: 60, q: "Everyone should have the right to freedom of speech.", topic: "Freedom of speech", fam: [7, 0], eng: ['E1', 'E2', 'E5'] },
    { id: 63, q: "Globalisation is making cultures around the world more similar.", topic: "Globalisation; cultural identity", fam: [7, 8], eng: ['E2', 'E5', 'E10'] },
    { id: 65, q: "It is better to travel with a tour guide than to travel independently.", topic: "Group vs independent travel", fam: [8, 1], eng: ['E1', 'E2', 'E10'] },
    // === Remaining Examword Questions (44) ===
    { id: 3, q: "If you want to be successful at work, you should have high-level computer skills. Do you agree or disagree?", topic: "Computer skills for work success", fam: [5, 2, 6], eng: ['E1', 'E4', 'E10'] },
    { id: 4, q: "Some people think that Mathematics is the most important subject for school children to study, while some disagree. Discuss both views and give your own opinion.", topic: "Mathematics as most important subject", fam: [6, 2], eng: ['E1', 'E2', 'E10'] },
    { id: 5, q: "Some people think that certain old buildings that are historically important in cities or the countryside should be preserved. Do you agree or disagree?", topic: "Preserving old buildings", fam: [7, 8, 0], eng: ['E5', 'E8', 'E10'] },
    { id: 6, q: "Many schoolchildren dislike learning maths. What are the reasons, and what are the best ways to make them enjoy maths?", topic: "Making maths enjoyable", fam: [6, 3], eng: ['E2', 'E6', 'E9'] },
    { id: 9, q: "Some people think that modern communication technology is having a negative effect on social relationships. To what extent do you agree or disagree?", topic: "Communication technology vs relationships", fam: [5, 1, 3], eng: ['E2', 'E6', 'E10'] },
    { id: 11, q: "Some people think rapid population growth in cities benefits people who live there, while others believe that it has negative impacts. Discuss both views and give your own opinion.", topic: "Rapid city population growth", fam: [8, 2, 4], eng: ['E1', 'E2', 'E7'] },
    { id: 12, q: "Some people think society could benefit more if more people study business than history. To what extent do you agree or disagree?", topic: "Business vs history study", fam: [6, 2], eng: ['E1', 'E2', 'E10'] },
    { id: 14, q: "An increasing number of people are changing careers during their working life. What do you think are the reasons for this? Do you think this is a positive or negative development for society?", topic: "Changing careers mid-life", fam: [2, 8, 1], eng: ['E1', 'E6', 'E10'] },
    { id: 16, q: "Many people believe that reducing the income gap between the rich and the poor can lead to a happier society. To what extent do you agree or disagree?", topic: "Reducing income gap", fam: [2, 7, 0], eng: ['E4', 'E7', 'E8'] },
    { id: 18, q: "Art classes, such as painting or drawing, are as important for children's development as other subjects, so they should be compulsory in high school. Do you agree or disagree?", topic: "Art classes compulsory in school", fam: [6, 7], eng: ['E1', 'E9', 'E10'] },
    { id: 20, q: "Long-distance flight consumes the amount of fuel that a car uses for many years and pollutes the air. Some people think that we should discourage non-essential flights, such as tourist travel, rather than limit the use of cars. To what extent do you agree or disagree?", topic: "Flights vs cars pollution", fam: [4, 0], eng: ['E2', 'E7', 'E10'] },
    { id: 22, q: "Some people think that the best way to succeed is to get a university education, while others disagree and say that it is no longer true nowadays. Discuss both views and give your own opinions.", topic: "University education for success", fam: [6, 2], eng: ['E1', 'E6', 'E10'] },
    { id: 23, q: "In the modern world, it is possible to communicate with people via the Internet without any face-to-face contact with others. Is it a positive or negative development?", topic: "Internet replacing face-to-face contact", fam: [5, 1, 3], eng: ['E1', 'E2', 'E10'] },
    { id: 24, q: "The values that we learn from our parents and family have a greater influence on our future success than the knowledge and skills we learn at school. To what extent do you agree or disagree?", topic: "Family values vs school knowledge", fam: [1, 6, 7], eng: ['E1', 'E6', 'E10'] },
    { id: 26, q: "Large companies should pay CEOs and executives higher salaries than other workers. To what extent do you agree or disagree?", topic: "CEO high salaries", fam: [2, 7, 1], eng: ['E2', 'E3', 'E10'] },
    { id: 27, q: "In some countries worldwide, men and women have children at a later age than in the past. What are the reasons for this development? What are the effects on society and family life?", topic: "Delayed parenthood trend", fam: [8, 1, 2], eng: ['E6', 'E7', 'E10'] },
    { id: 28, q: "Some students choose to travel after leaving school and before going to university. Many people, however, say that working experience is more useful in adult life than travel. Do you agree or disagree?", topic: "Gap year: travel vs work experience", fam: [8, 6, 2], eng: ['E1', 'E2', 'E10'] },
    { id: 29, q: "Some people think that the increasing use of computers and mobile phones for communication hurts young people's reading and writing skills. Do you agree or disagree?", topic: "Technology hurting literacy skills", fam: [5, 6, 1], eng: ['E2', 'E6', 'E9'] },
    { id: 30, q: "Some people think that individuals are becoming more dependent on each other in modern society, while others believe that individuals are becoming more independent of each other. Discuss both views and give your own opinion.", topic: "Interdependence vs independence in society", fam: [1, 5, 8], eng: ['E1', 'E6', 'E10'] },
    { id: 32, q: "Health services are a basic necessity. However, private companies have made them quite costly for ordinary individuals. Do the advantages of private health care outweigh its disadvantages?", topic: "Private vs public healthcare", fam: [0, 3, 2], eng: ['E1', 'E3', 'E10'] },
    { id: 33, q: "Some people think the government should not spend on international aid because there are disadvantaged people in their countries, such as the unemployed and homeless. To what extent do you agree or disagree?", topic: "International aid vs domestic issues", fam: [0, 2, 1], eng: ['E3', 'E8', 'E10'] },
    { id: 34, q: "Mobile phones and the internet could have many benefits for older adults. However, this age group uses technology the least. What are the benefits for older adults of using mobile phones and the internet? How can we encourage them to use this new technology?", topic: "Technology benefits for older adults", fam: [5, 1], eng: ['E1', 'E4', 'E9'] },
    { id: 36, q: "Since most information about culture and history can be found online, museums and art galleries are no longer needed. To what extent do you agree or disagree?", topic: "Museums vs online information", fam: [5, 7, 0], eng: ['E2', 'E5', 'E10'] },
    { id: 37, q: "Some people think technology development decreases crime, while others believe it actually encourages crime. Discuss both views and give your own opinion.", topic: "Technology and crime", fam: [5, 0, 7], eng: ['E1', 'E2', 'E10'] },
    { id: 38, q: "Some people think most crimes are the result of circumstances like poverty and other social problems. Others believe that they are caused by people who are bad in nature. Discuss both views and give your own opinion.", topic: "Crime: poverty vs nature", fam: [2, 7, 0], eng: ['E2', 'E6', 'E11'] },
    { id: 39, q: "Some people think that advertising may have positive economic effects. Others think it has negative social effects because advertising makes individuals less satisfied with what they are and have. Discuss both views and give your own opinion.", topic: "Advertising: economic vs social effects", fam: [2, 5, 3], eng: ['E1', 'E2', 'E10'] },
    { id: 41, q: "Nowadays, a person's worth seems to be judged according to social status and material possessions. Old-fashioned values, such as honor, kindness, and trust, no longer seem important. To what extent do you agree or disagree?", topic: "Social status vs traditional values", fam: [7, 2], eng: ['E2', 'E6', 'E10'] },
    { id: 43, q: "Some people argue that it is more important to have an enjoyable job than to earn a lot of money. Others disagree and think that a good salary leads to a better life. Discuss both views and give your own opinion.", topic: "Enjoyable job vs good salary", fam: [2, 3, 7], eng: ['E1', 'E2', 'E10'] },
    { id: 44, q: "Safety standards are important when building people's homes. Who should be responsible for enforcing strict building codes – the government or the people who build the homes?", topic: "Building safety responsibility", fam: [8, 0], eng: ['E8', 'E6', 'E10'] },
    { id: 45, q: "We are becoming increasingly dependent on computers. They are used in business, hospitals, crime detection, and even to fly planes. What things will they be used in the future? Is this dependence on computers a good thing, or should we be more suspicious of their benefits?", topic: "Computer dependency", fam: [5, 2], eng: ['E1', 'E2', 'E5'] },
    { id: 46, q: "Successful sports professionals can earn much more than those in other important professions, like nurses, doctors, and teachers. Some people think it is fully justified, while others believe it is unfair. To what extent do you agree or disagree?", topic: "Sports professionals' high earnings", fam: [2, 7, 1], eng: ['E2', 'E3', 'E10'] },
    { id: 47, q: "Some people think that professional athletes make good role models for young people, while others believe they don't. Discuss both views and give your own opinion.", topic: "Athletes as role models", fam: [1, 7, 6], eng: ['E1', 'E2', 'E10'] },
    { id: 48, q: "A growing number of people feel that people should not exploit animals and animals have the same rights as humans. In contrast, others argue that humans must employ animals to satisfy their various needs, including food and research uses. Discuss both views and give your opinion.", topic: "Animal rights vs human needs", fam: [7, 3], eng: ['E2', 'E5', 'E10'] },
    { id: 49, q: "Some people believe that it is the responsibility of individuals to take care of their health and diet. Others, however, believe that governments should ensure their citizens have a healthy diet. Discuss both views and give your opinion.", topic: "Health responsibility: individual vs government", fam: [0, 3, 7], eng: ['E8', 'E10', 'E11'] },
    { id: 51, q: "Some people think that parents should teach children how to be good members of society. Others, however, believe that school is the place to learn this. Discuss both views and give your own opinion.", topic: "Parents vs school: teaching social values", fam: [6, 1, 7], eng: ['E9', 'E6', 'E10'] },
    { id: 52, q: "Increasing the petrol price is the best way to solve the growing traffic and pollution problems. To what extent do you agree or disagree?", topic: "Petrol price increase for pollution", fam: [4, 0, 2], eng: ['E2', 'E8', 'E10'] },
    { id: 53, q: "Around the world, children learn English as a second language at school. However, in some places, they also learn at kindergarten. Discuss the advantages and disadvantages of learning English at kindergarten.", topic: "English learning at kindergarten", fam: [6, 8], eng: ['E1', 'E2', 'E10'] },
    { id: 54, q: "Some different medical traditions are now widely known and used: Western medicine, herbal medicine, acupuncture, homeopathy, etc. How important is the patient's mental attitude towards treatment in determining its effectiveness?", topic: "Medical traditions and mental attitude", fam: [8, 3], eng: ['E1', 'E6', 'E10'] },
    { id: 56, q: "Modern appliances have become more common in the home, leaving no doubt that technological advances have improved our lifestyle. Do you agree or disagree?", topic: "Modern appliances improving lifestyle", fam: [5, 8], eng: ['E1', 'E6', 'E10'] },
    { id: 57, q: "There are so many examples to prove that attitude is as important as knowledge in a test situation. Attitude can also change your situation. To what extent do you agree?", topic: "Attitude vs knowledge in tests", fam: [7, 6], eng: ['E1', 'E6', 'E12'] },
    { id: 59, q: "In many countries, people are concerned about the number of overweight children. What do you think are the causes of this?", topic: "Overweight children causes", fam: [3, 1, 6], eng: ['E2', 'E6', 'E9'] },
    { id: 61, q: "Many students choose to attend schools or universities outside their home countries. Why do some students study abroad?", topic: "Reasons for studying abroad", fam: [8, 6], eng: ['E1', 'E4', 'E12'] },
    { id: 62, q: "Besides many advantages, some believe the Internet creates many problems. To what extent do you agree or disagree?", topic: "Internet advantages vs problems", fam: [5, 3, 0], eng: ['E1', 'E2', 'E8'] },
    { id: 64, q: "Problems with environmental pollution have become so severe that many countries are trying to solve these problems. Suggest possible solutions and give your own opinion.", topic: "Environmental pollution solutions", fam: [4, 0], eng: ['E2', 'E8', 'E5'] },
    // === Band 8 Essays (22) ===
    { id: 101, q: "In many countries, smoking is now illegal in public places. Many people believe that such a ban is justified. Do you agree or disagree?", topic: "Smoking ban in public places", fam: [0, 3], eng: ['E2', 'E3', 'E8', 'E11', 'E12'] },
    { id: 102, q: "Some people think that a sense of competition in children should be encouraged. Others believe that children who are taught to cooperate rather than compete become more useful adults. Discuss both views and give your own opinion.", topic: "Competition vs cooperation in children", fam: [1, 6, 3], eng: ['E2', 'E1', 'E10', 'E11', 'E12'] },
    { id: 103, q: "Some parents think that childcare centres provide the best services for children of preschool age. Other working parents think that family members such as grandparents are better caregivers. Discuss both views and give your opinion.", topic: "Childcare: family vs daycare centres", fam: [1, 6], eng: ['E1', 'E2', 'E10'] },
    { id: 104, q: "Life was better when technology was simpler. To what extent do you agree or disagree?", topic: "Life was better with simpler technology", fam: [5, 3, 2], eng: ['E1', 'E2', 'E7'] },
    { id: 105, q: "At present, the media affects people's lives significantly. What impact does this have on society? Is it a negative or positive development?", topic: "Media's impact on society", fam: [5, 3, 7], eng: ['E2', 'E6', 'E5'] },
    { id: 106, q: "Some believe that money is the main reason people stay working for the same company. Do you agree or disagree?", topic: "Money as main reason to stay in a job", fam: [2, 3, 1], eng: ['E1', 'E2', 'E10'] },
    { id: 107, q: "Who do you think should pay for elderly care, the government or the family?", topic: "Who should pay for elderly care", fam: [0, 2, 1], eng: ['E3', 'E8', 'E10'] },
    { id: 108, q: "Obesity is a major disease prevalent among children. What are its causes, and what solutions can be offered?", topic: "Childhood obesity", fam: [3, 6, 1], eng: ['E2', 'E6', 'E9', 'E12'] },
    { id: 109, q: "In many countries, children are engaged in some kind of paid work. Some people regard this as completely wrong, while others consider it as valuable work experience. Discuss both views and give your opinion.", topic: "Children and paid work", fam: [1, 6, 2], eng: ['E2', 'E1', 'E10', 'E11'] },
    { id: 110, q: "Air transport is increasingly used to export fruit and vegetables to countries where they cannot be grown or are out of season. What are the advantages and disadvantages of this?", topic: "Air transport of food", fam: [4, 3], eng: ['E1', 'E2', 'E7', 'E12'] },
    { id: 111, q: "Some people get into debt by buying things they do not need and cannot afford. What are the reasons for this behaviour? What action can be taken to prevent it?", topic: "Debt from unnecessary purchases", fam: [2, 3, 6], eng: ['E2', 'E6', 'E9'] },
    { id: 112, q: "People naturally resist making changes in their lives. What kinds of problems can this cause? What solutions can you suggest?", topic: "Resistance to change", fam: [3, 2, 1], eng: ['E2', 'E4', 'E6'] },
    { id: 113, q: "Many museums charge for admission, while others are free. Do you think the advantages of charging people for admission to museums outweigh the disadvantages?", topic: "Museum admission fees", fam: [2, 7, 0], eng: ['E3', 'E1', 'E10'] },
    { id: 114, q: "What are the factors that contribute to job satisfaction? How realistic is the expectation of job satisfaction for all workers?", topic: "Job satisfaction", fam: [2, 3, 1], eng: ['E1', 'E6', 'E10'] },
    { id: 115, q: "A person's worth nowadays seems to be judged according to social status and material possessions. Old-fashioned values such as honour, kindness, and trust no longer seem important. To what extent do you agree or disagree?", topic: "Social status vs old-fashioned values", fam: [7, 2], eng: ['E2', 'E6', 'E10'] },
    { id: 116, q: "What are the most serious problems associated with the internet and what are the possible solutions?", topic: "Internet problems and solutions", fam: [5, 3, 0], eng: ['E2', 'E8', 'E9'] },
    { id: 117, q: "In some countries, many more people are choosing to live alone nowadays than in the past. Do you think this is a positive or negative development?", topic: "Living alone trend", fam: [8, 3, 2], eng: ['E1', 'E6', 'E7', 'E12'] },
    { id: 118, q: "Wealthy countries should accept more refugees and provide them with basic assistance such as food and housing. To what extent do you agree or disagree?", topic: "Wealthy countries and refugees", fam: [0, 7, 2], eng: ['E1', 'E8', 'E4', 'E11', 'E12'] },
    { id: 119, q: "Governments give lots of support to artists, even though some people think it is a waste of money that could have been spent better elsewhere. Discuss both views and give your opinion.", topic: "Government funding for artists", fam: [0, 2, 7], eng: ['E3', 'E1', 'E10', 'E11'] },
    { id: 120, q: "More and more people in developing countries are purchasing cars for the first time. What problems does this cause? What do you think are some possible solutions?", topic: "Cars in developing countries", fam: [4, 3, 0], eng: ['E2', 'E8', 'E5', 'E12'] },
    { id: 121, q: "Many teenagers have their own smartphones. Does this situation have more advantages or more disadvantages?", topic: "Teenagers and smartphones", fam: [5, 1, 3], eng: ['E1', 'E2', 'E10'] },
    { id: 122, q: "Climate change is the biggest threat to life on our planet. How accurate is this statement? Are there any other big threats to mankind?", topic: "Climate change vs nuclear weapons", fam: [4, 0, 3], eng: ['E5', 'E7', 'E10'] },
    // === Art (8) ===
    { id: 200, q: "Art is not as important in today's world as science. To what extent do you agree?", topic: "Art vs science importance", fam: [7, 6], eng: ['E2', 'E6', 'E10'] },
    { id: 201, q: "International art and literature is essential in today's world. Do you agree?", topic: "International art and literature", fam: [7, 8], eng: ['E1', 'E6', 'E10'] },
    { id: 202, q: "Many people support the arts. Why is that?", topic: "Why people support arts", fam: [7, 0], eng: ['E1', 'E6', 'E7'] },
    { id: 203, q: "The government should spend more money supporting the arts, while others think funding should go on health care and education. Discuss both sides and give your opinion.", topic: "Government arts funding vs health/education", fam: [0, 7, 3], eng: ['E3', 'E8', 'E10'] },
    { id: 204, q: "Traditional arts should be preserved better. Do you agree? How can this be done?", topic: "Preserving traditional arts", fam: [7, 0], eng: ['E5', 'E8', 'E1'] },
    { id: 205, q: "Many people believe the arts should be censored. Do you agree?", topic: "Arts censorship", fam: [7, 0], eng: ['E2', 'E5', 'E10'] },
    { id: 206, q: "Social media is changing the way we appreciate art. Is this a positive or negative trend?", topic: "Social media and art appreciation", fam: [5, 7], eng: ['E1', 'E2', 'E6'] },
    { id: 207, q: "Art is a healthy hobby and more people should be encouraged to take it up as a hobby. What is your opinion?", topic: "Art as healthy hobby", fam: [3, 7], eng: ['E1', 'E4', 'E9'] },
    // === Books & Reading (3) ===
    { id: 210, q: "Schools and parents should encourage children to read more.", topic: "Encouraging children to read", fam: [6, 1], eng: ['E1', 'E9', 'E4'] },
    { id: 211, q: "What are the advantages and disadvantages of e-books?", topic: "E-books pros and cons", fam: [5, 6], eng: ['E1', 'E2', 'E10'] },
    { id: 212, q: "The government should stop supporting public libraries because most information is available online.", topic: "Public libraries vs online info", fam: [0, 5, 6], eng: ['E2', 'E5', 'E10'] },
    // === Business & Money (9) ===
    { id: 220, q: "It is better to work for yourself than for a company. What are the advantages and disadvantages of doing so?", topic: "Self-employment vs company work", fam: [2, 1], eng: ['E1', 'E2', 'E10'] },
    { id: 221, q: "Many people are spending money rather than saving it. Is this a positive or negative trend?", topic: "Spending vs saving money", fam: [2, 1], eng: ['E2', 'E6', 'E5'] },
    { id: 222, q: "Small local businesses are being threatened by large chain stores. Why is this? What can be done about it?", topic: "Local business vs chain stores", fam: [2, 0], eng: ['E2', 'E6', 'E8'] },
    { id: 223, q: "People should be encouraged to buy only domestic products, not foreign products. Others think we should be able to buy what we prefer. Discuss both sides and give your opinion.", topic: "Domestic vs foreign products", fam: [2, 0, 7], eng: ['E1', 'E2', 'E10'] },
    { id: 224, q: "No children should leave school without learning how to manage money. Do you agree?", topic: "Money management in school", fam: [2, 6], eng: ['E2', 'E9', 'E4'] },
    { id: 225, q: "Many people go into personal debt. Why is this? What can be done about it?", topic: "Personal debt causes and solutions", fam: [2, 6], eng: ['E2', 'E6', 'E9'] },
    { id: 226, q: "Many people spend too much money on luxury goods and special events. Why is this? Is it a positive or negative trend?", topic: "Luxury spending trend", fam: [2, 8], eng: ['E2', 'E6', 'E7'] },
    { id: 227, q: "Having a good product is the best way to be successful in business. Do you agree?", topic: "Good product for business success", fam: [2], eng: ['E1', 'E6', 'E10'] },
    { id: 228, q: "Many companies use open-plan office spaces. What are the advantages and disadvantages of this?", topic: "Open-plan offices", fam: [2, 3], eng: ['E1', 'E2', 'E10'] },
    // === Character & People (7) ===
    { id: 230, q: "Some people work harder than others. Why is this? Can someone learn how to work hard?", topic: "Why people work harder", fam: [1, 7], eng: ['E6', 'E4', 'E9'] },
    { id: 231, q: "Old people have a better understanding of life. To what extent do you agree?", topic: "Old people understanding life", fam: [1, 7], eng: ['E1', 'E6', 'E10'] },
    { id: 232, q: "Old people are becoming less respected by society and by the younger generation. Why is this happening? What can be done about it?", topic: "Respect for elderly declining", fam: [1, 7], eng: ['E2', 'E6', 'E9'] },
    { id: 233, q: "Some people follow trends, while other people set them. Why do you think this is? Do you think it is better to set trends or follow them?", topic: "Setting vs following trends", fam: [8, 7], eng: ['E1', 'E6', 'E10'] },
    { id: 234, q: "Some people are born to be successful. Do you agree?", topic: "Born to be successful", fam: [1, 7], eng: ['E2', 'E6', 'E10'] },
    { id: 235, q: "Do you think character is innate or something we can cultivate? How can we develop our character?", topic: "Innate vs cultivated character", fam: [7, 6], eng: ['E6', 'E4', 'E10'] },
    { id: 236, q: "Should schools encourage individuality or conformity? Which one is most beneficial for a child's future?", topic: "Individuality vs conformity in schools", fam: [6, 7], eng: ['E1', 'E2', 'E10'] },
    // === Crime & Punishment (7) ===
    { id: 240, q: "It would be quicker if there was the same punishment for the same crimes, but some people think this is not a good policy because circumstances should be considered. Discuss both sides and give your opinion.", topic: "Same punishment for same crimes", fam: [0, 7], eng: ['E2', 'E6', 'E10'] },
    { id: 241, q: "Too many criminals leave prison only to reoffend. Why is this? What measures can be introduced to solve this problem?", topic: "Criminals reoffending after prison", fam: [0, 7], eng: ['E2', 'E6', 'E8'] },
    { id: 242, q: "Crime rates are increasing in many cities. Why is this? How can this be tackled?", topic: "Increasing crime rates", fam: [0, 1], eng: ['E2', 'E7', 'E8'] },
    { id: 243, q: "Some people think violent films encourage criminal behaviour. To what extent do you agree?", topic: "Violent films and crime", fam: [5, 7], eng: ['E2', 'E6', 'E7'] },
    { id: 244, q: "Some teenagers commit serious crime. Some people think they should get the same punishment as adults, while others disagree. Discuss both sides and give your opinion.", topic: "Teenage crime punishment", fam: [0, 1, 7], eng: ['E2', 'E8', 'E10'] },
    { id: 245, q: "Why are crime shows so popular on TV? Do you think this is a positive or negative trend?", topic: "Crime shows popularity on TV", fam: [5, 7], eng: ['E1', 'E2', 'E6'] },
    { id: 246, q: "Is personal safety a government responsibility or the responsibility of the individual?", topic: "Personal safety responsibility", fam: [0, 7], eng: ['E8', 'E6', 'E10'] },
    // === Culture & Tourism (7) ===
    { id: 250, q: "Nearly all cities have museums or art galleries. Some people think they are a waste of funds, others disagree. Discuss both sides and give your opinion.", topic: "Museums as waste of funds", fam: [0, 7, 2], eng: ['E3', 'E1', 'E10'] },
    { id: 251, q: "Social media has brought with it globalisation. Do you think it is a positive or negative trend?", topic: "Social media and globalisation", fam: [5, 7], eng: ['E1', 'E2', 'E10'] },
    { id: 252, q: "Traditional lifestyles are slowly being forgotten. Do you think this is a bad thing? What can be done about it?", topic: "Traditional lifestyles forgotten", fam: [7, 8], eng: ['E2', 'E5', 'E8'] },
    { id: 253, q: "Tourism to remote areas in the world is becoming more popular. Why is this? What impact does this have on local cultures?", topic: "Tourism to remote areas", fam: [8, 7, 4], eng: ['E1', 'E2', 'E6'] },
    { id: 254, q: "Some people think the world will one day have only one language. To what extent do you agree? Would this be a good thing?", topic: "One world language", fam: [7, 8], eng: ['E4', 'E5', 'E10'] },
    { id: 255, q: "All countries around the world celebrate national holidays. What role do they play? How important are they?", topic: "National holidays importance", fam: [7, 0], eng: ['E1', 'E6', 'E7'] },
    { id: 256, q: "People should be encouraged to take holidays in their own country to boost the economy. To what extent do you agree?", topic: "Domestic holidays for economy", fam: [2, 8], eng: ['E1', 'E4', 'E10'] },
    // === Education (13) ===
    { id: 260, q: "Schools should do more to instill discipline in students. How should this be done? Do you think the parents should take some responsibility for this?", topic: "School discipline", fam: [6, 1], eng: ['E8', 'E9', 'E10'] },
    { id: 261, q: "Some people think children should be grouped together into classes, others do not agree. Discuss both sides and give your opinion.", topic: "Grouping children into classes", fam: [6, 1], eng: ['E1', 'E2', 'E10'] },
    { id: 262, q: "More and more people are choosing to educate themselves online. What are the advantages and disadvantages of this?", topic: "Online education", fam: [6, 5], eng: ['E1', 'E2', 'E10'] },
    { id: 263, q: "Some people think that traditional subjects at school are a waste of time because soft skills and experience are more important to get a good job. Do you agree?", topic: "Traditional subjects vs soft skills", fam: [6, 2], eng: ['E2', 'E6', 'E10'] },
    { id: 264, q: "Some people think the best way to get a good job is to have a university education. To what extent do you agree?", topic: "University education for good jobs", fam: [6, 2], eng: ['E1', 'E6', 'E10'] },
    { id: 265, q: "Schools should give children more homework to help their academic learning. Do you think this is a good idea?", topic: "More homework for children", fam: [6, 3], eng: ['E1', 'E2', 'E10'] },
    { id: 266, q: "As children grow up they spend time both at school and at home. Do you think parents or teachers influence a child most?", topic: "Parents vs teachers influence", fam: [6, 1], eng: ['E6', 'E1', 'E10'] },
    { id: 267, q: "Some people think schools should teach children right from wrong, while other people think this responsibility should fall on the parents. Discuss both sides and give your opinion.", topic: "Schools vs parents teaching morals", fam: [6, 1, 7], eng: ['E2', 'E9', 'E10'] },
    { id: 268, q: "Education should be free for everyone. To what extent do you agree?", topic: "Free education for all", fam: [6, 0, 2], eng: ['E3', 'E8', 'E10'] },
    { id: 269, q: "Some people think that history is a useful subject to learn, while others think it is a waste of time. What do you think?", topic: "History as useful subject", fam: [6, 7], eng: ['E1', 'E2', 'E10'] },
    { id: 270, q: "Education in rural areas is often not as good as in cities. Why is that? What do you think can be done about it?", topic: "Rural vs urban education", fam: [6, 0, 2], eng: ['E2', 'E7', 'E8'] },
    { id: 271, q: "Many children think school is boring and this attitude can affect their academic results. What solutions can you suggest for this problem?", topic: "School boredom", fam: [6, 1], eng: ['E2', 'E6', 'E9'] },
    { id: 272, q: "Having a gap year between school and university is a popular choice for many students. Do you think this is a positive trend?", topic: "Gap year between school and university", fam: [6, 8], eng: ['E1', 'E2', 'E10'] },
    // === Environment, Nature & Wildlife (6) ===
    { id: 280, q: "Many species are becoming extinct. Do you think this is a problem? What can be done about it?", topic: "Species extinction problem", fam: [4, 7], eng: ['E2', 'E5', 'E8'] },
    { id: 281, q: "Do you think it is the government's or the individual's responsibility to protect the environment?", topic: "Environment protection responsibility", fam: [4, 0, 7], eng: ['E8', 'E6', 'E10'] },
    { id: 282, q: "Many people throw litter on to the streets or in green spaces. Why is this a problem? What solutions can you suggest?", topic: "Littering problem", fam: [4, 0], eng: ['E2', 'E6', 'E8'] },
    { id: 283, q: "Many drug companies and make up companies test their products on animals. Do you think this is right?", topic: "Animal testing for products", fam: [7, 3], eng: ['E2', 'E5', 'E10'] },
    { id: 284, q: "Beauty spots are often tourist attractions. What problems does this cause? What can be done about it?", topic: "Tourism at beauty spots", fam: [4, 8], eng: ['E2', 'E6', 'E8'] },
    { id: 285, q: "Many people are concerned about Climate Change. What problems does it cause? What solutions are there?", topic: "Climate change problems and solutions", fam: [4, 0], eng: ['E2', 'E5', 'E8'] },
    // === Family (7) ===
    { id: 290, q: "Children have less respect for their elders than in the past. Why is this? What can be done about it?", topic: "Children respect for elders", fam: [1, 7], eng: ['E2', 'E6', 'E9'] },
    { id: 291, q: "Some people think grandparents have a lot to teach their grandchildren, while others think they are too out of date to connect with them. Discuss both sides and give your opinion.", topic: "Grandparents teaching grandchildren", fam: [1, 7], eng: ['E1', 'E2', 'E10'] },
    { id: 292, q: "Some people think the government should take care of the elderly, while others think the family should. Discuss both sides and give your opinion.", topic: "Government vs family elderly care", fam: [0, 1, 2], eng: ['E3', 'E8', 'E10'] },
    { id: 293, q: "In the modern world, fewer families are eating their meals together. Why is this? Is it a positive or negative trend?", topic: "Family meals declining", fam: [1, 8, 3], eng: ['E2', 'E6', 'E5'] },
    { id: 294, q: "Many families do not spend much time communicating with each other. What are the reasons for this? What can be done about it?", topic: "Family communication decline", fam: [1, 5], eng: ['E2', 'E6', 'E9'] },
    { id: 295, q: "Some women choose not to have children. Why is this? Is it this a positive or negative trend?", topic: "Women choosing not to have children", fam: [1, 8, 7], eng: ['E1', 'E6', 'E10'] },
    { id: 296, q: "Some people think parents should be strict, but others think children need more freedom to make their own choices. Discuss both sides and give your opinion.", topic: "Strict parents vs children freedom", fam: [1, 7], eng: ['E1', 'E2', 'E10'] },
    // === Food (4) ===
    { id: 300, q: "Traditional food is becoming less popular. Do you think this is a problem? What can be done about it?", topic: "Traditional food declining", fam: [8, 7], eng: ['E2', 'E5', 'E8'] },
    { id: 301, q: "More and more children are eating junk food. What are the reasons for this? What can be done to solve this?", topic: "Children eating junk food", fam: [3, 1, 6], eng: ['E2', 'E6', 'E9'] },
    { id: 302, q: "Some people eat only organic food. What is the reason for this? Do you think it is a positive or negative trend?", topic: "Organic food trend", fam: [3, 8], eng: ['E1', 'E6', 'E7'] },
    { id: 303, q: "Some people think cooking should be taught in schools, while other people think children should learn this at home. Discuss both sides and give your opinion.", topic: "Cooking in schools vs home", fam: [6, 1, 8], eng: ['E9', 'E1', 'E10'] },
    // === Health & Exercise (11) ===
    { id: 310, q: "Schools should increase the number of sports and exercises classes to help children develop into healthy adults. What is your opinion?", topic: "More sports in schools", fam: [6, 3], eng: ['E1', 'E9', 'E4'] },
    { id: 311, q: "It is the schools responsibility, not the parent's responsibility to teach children what healthy food is. To what extent do you agree?", topic: "School vs parent health education", fam: [6, 1, 3], eng: ['E9', 'E2', 'E10'] },
    { id: 312, q: "Too many children spend most of their free time using screens. Why is this a problem? What solutions can you suggest?", topic: "Children screen time", fam: [5, 3, 1], eng: ['E2', 'E6', 'E9'] },
    { id: 313, q: "Many schools teach team sports in schools. Why is this?", topic: "Team sports in schools", fam: [6, 3], eng: ['E1', 'E6', 'E9'] },
    { id: 314, q: "More and more adults are starting to prioritise their mental health. Why is this? Do you think this is a positive or negative trend?", topic: "Adults prioritising mental health", fam: [3, 1], eng: ['E1', 'E6', 'E7'] },
    { id: 315, q: "Many people commute to work by car or public transport, but not by cycling or walking. What are the advantages and disadvantages of this?", topic: "Commuting by car vs cycling", fam: [4, 3, 8], eng: ['E1', 'E2', 'E10'] },
    { id: 316, q: "The government should spend less money on trying to cure illnesses and more money on preventing them. Do you agree?", topic: "Cure vs prevention spending", fam: [0, 3, 2], eng: ['E3', 'E8', 'E10'] },
    { id: 317, q: "Health care should be free for all people. To what extent do you agree?", topic: "Free healthcare for all", fam: [0, 3, 2], eng: ['E3', 'E8', 'E10'] },
    { id: 318, q: "Some sports professionals earn more money than doctors or nurses. Do you think this is right?", topic: "Sports vs medical pay", fam: [2, 7, 1], eng: ['E2', 'E6', 'E10'] },
    { id: 319, q: "International sporting events are very popular. Why is this?", topic: "International sporting events popularity", fam: [7, 2], eng: ['E1', 'E6', 'E7'] },
    { id: 320, q: "Hobbies are healthy activities all adults should have. Do you agree?", topic: "Hobbies for adult health", fam: [3, 8], eng: ['E1', 'E4', 'E6'] },
    // === Language & Communication (4) ===
    { id: 330, q: "More and more people are doing business and conducting meetings through video call online. What are the advantages and disadvantages of this?", topic: "Online video meetings", fam: [5, 2], eng: ['E1', 'E2', 'E10'] },
    { id: 331, q: "Globalisation has brought the world closer together. Some people think countries will eventually become very similar. To what extent do you agree?", topic: "Globalisation making countries similar", fam: [7, 8], eng: ['E2', 'E5', 'E10'] },
    { id: 332, q: "The world will one day have only one language. To what extent do you agree?", topic: "One global language", fam: [7, 8], eng: ['E4', 'E5', 'E10'] },
    { id: 333, q: "Children should all learn a foreign language to thrive in today's modern world. Do you agree?", topic: "Children learning foreign language", fam: [6, 8], eng: ['E1', 'E4', 'E9'] },
    // === Media & The Internet (11) ===
    { id: 340, q: "The internet has changed the way we shop. Do you think this is a positive or negative trend?", topic: "Internet shopping trend", fam: [5, 2], eng: ['E1', 'E2', 'E10'] },
    { id: 341, q: "Has the internet made our world less safe? What is your opinion?", topic: "Internet and safety", fam: [5, 0], eng: ['E2', 'E6', 'E8'] },
    { id: 342, q: "More people are watching Netflix and other streaming services online. Why is this? Do you think this is a good change?", topic: "Streaming services popularity", fam: [5, 8], eng: ['E1', 'E6', 'E10'] },
    { id: 343, q: "Some people get their news from the internet, while other people do not trust the news they read online. Discuss both sides and give your opinion.", topic: "Online news trust", fam: [5, 7], eng: ['E1', 'E2', 'E10'] },
    { id: 344, q: "Some people think newspapers will one day die out in favour of online news. To what extent do you agree?", topic: "Newspapers dying out", fam: [5, 7], eng: ['E4', 'E6', 'E10'] },
    { id: 345, q: "More people are becoming famous because of reality shows. Do you think this is a positive or negative trend?", topic: "Reality show fame", fam: [5, 1, 7], eng: ['E2', 'E6', 'E10'] },
    { id: 346, q: "Many young children look up to actors and actresses as role models. What are the advantages and disadvantages of this?", topic: "Celebrity role models", fam: [1, 7, 5], eng: ['E1', 'E2', 'E10'] },
    { id: 347, q: "Children enjoy socialising online. Is this a positive or negative trend?", topic: "Children socialising online", fam: [5, 1, 3], eng: ['E1', 'E2', 'E10'] },
    { id: 348, q: "Many celebrities complain about their lack of privacy from the media. Do you think celebrities have the right to privacy?", topic: "Celebrity privacy rights", fam: [7, 5, 1], eng: ['E2', 'E6', 'E10'] },
    { id: 349, q: "Many celebrities have cosmetic surgery. Is this a positive or negative trend?", topic: "Celebrity cosmetic surgery", fam: [3, 7, 1], eng: ['E2', 'E6', 'E10'] },
    { id: 350, q: "Adverts for products often entice people to buy products they do not need. Why is this? Is this a problem?", topic: "Advertising and unnecessary purchases", fam: [2, 5], eng: ['E2', 'E6', 'E7'] },
    // === Technology (6) ===
    { id: 360, q: "Some people think that teachers will one day be replaced in the classroom by technology. To what extent do you agree?", topic: "Technology replacing teachers", fam: [5, 6], eng: ['E4', 'E2', 'E10'] },
    { id: 361, q: "Some people think that the more technology develops, the fewer jobs there will be. To what extent do you agree?", topic: "Technology reducing jobs", fam: [5, 2], eng: ['E4', 'E5', 'E7'] },
    { id: 362, q: "Most people own a smart phone. What are the benefits of a smart phone? Are there any disadvantages?", topic: "Smartphone benefits and disadvantages", fam: [5, 3], eng: ['E1', 'E2', 'E10'] },
    { id: 363, q: "Some images and videos online are created by AI. What are the advantages and disadvantages of this?", topic: "AI-generated content", fam: [5, 7], eng: ['E1', 'E2', 'E10'] },
    { id: 364, q: "Some people think that AI will one day dominate humanity. To what extent do you agree?", topic: "AI dominating humanity", fam: [5, 7], eng: ['E4', 'E5', 'E10'] },
    { id: 365, q: "Some countries spend a lot of money on space exploration. What are the advantages and disadvantages of this?", topic: "Space exploration spending", fam: [2, 0, 5], eng: ['E3', 'E4', 'E10'] },
    // === Transport (5) ===
    { id: 370, q: "More and more cities are struggling with air pollution. Why is this? What solutions can you suggest?", topic: "City air pollution", fam: [4, 0], eng: ['E2', 'E7', 'E8'] },
    { id: 371, q: "Budget air travel has become increasingly popular. What problems has this caused?", topic: "Budget air travel problems", fam: [4, 2], eng: ['E2', 'E6', 'E7'] },
    { id: 372, q: "Electric cars are the way forward to a cleaner world. Do you agree?", topic: "Electric cars for cleaner world", fam: [4, 5], eng: ['E1', 'E4', 'E10'] },
    { id: 373, q: "City centres often have traffic congestion. What problems does this cause? How can traffic congestion be resolved?", topic: "Traffic congestion solutions", fam: [4, 0, 3], eng: ['E2', 'E8', 'E6'] },
    { id: 374, q: "Some countries invest more money on public transport, while other countries invest more money on expanding roads for private vehicles. Discuss both sides and give your opinion.", topic: "Public transport vs private roads", fam: [0, 4, 2], eng: ['E3', 'E8', 'E10'] },
    // === Work (6) ===
    { id: 380, q: "Working hard is the only way to be successful. Do you agree?", topic: "Hard work and success", fam: [2, 7], eng: ['E1', 'E6', 'E10'] },
    { id: 381, q: "Why do so many people prefer working remotely from home or elsewhere? Are there any downsides to this?", topic: "Remote work preference", fam: [2, 3, 5], eng: ['E1', 'E2', 'E6'] },
    { id: 382, q: "Many people around the world work very long hours. Why is this? Do you think this is a good thing?", topic: "Long working hours", fam: [2, 3], eng: ['E2', 'E6', 'E10'] },
    { id: 383, q: "Some people do work they love, others do work solely for money. Discuss both sides and give your opinion.", topic: "Work passion vs money", fam: [2, 3, 7], eng: ['E1', 'E2', 'E10'] },
    { id: 384, q: "Some companies seek people who are team players, while other companies prefer people who are independent workers. Discuss both sides and give your opinion.", topic: "Team players vs independent workers", fam: [2, 1], eng: ['E1', 'E2', 'E10'] },
    { id: 385, q: "In many families, both parents work. How does this impact their children? Is this a positive or negative trend?", topic: "Both parents working", fam: [1, 2, 3], eng: ['E1', 'E2', 'E10'] },
    // === World & Social Issues (9) ===
    { id: 390, q: "Poor countries need financial aid from richer countries. Do you think rich countries have an obligation to financially support poorer countries?", topic: "Financial aid for poor countries", fam: [0, 2, 7], eng: ['E8', 'E4', 'E10'] },
    { id: 391, q: "People are living longer than in the past. Why is this? What problems does this cause?", topic: "People living longer", fam: [3, 0, 2], eng: ['E1', 'E6', 'E7'] },
    { id: 392, q: "Some schools encourage children to do volunteer work. What are the advantages and disadvantages of this?", topic: "Volunteer work for children", fam: [6, 7], eng: ['E1', 'E2', 'E10'] },
    { id: 393, q: "In some countries, many people are moving out of cities to the countryside. Why is this? Is this a positive or negative trend?", topic: "Moving from cities to countryside", fam: [8, 4], eng: ['E1', 'E2', 'E6'] },
    { id: 394, q: "The government should focus on building new housing for the growing population, not renovating existing old buildings. To what extent do you agree?", topic: "New housing vs old buildings", fam: [0, 8], eng: ['E3', 'E8', 'E10'] },
    { id: 395, q: "Due to the growing population, some people think that companies should be relocated to the countryside. Do you agree?", topic: "Relocating companies to countryside", fam: [0, 2, 8], eng: ['E4', 'E8', 'E10'] },
    { id: 396, q: "In some countries, many workers move to the city to find work. Is this a positive or negative trend?", topic: "Workers moving to cities", fam: [2, 8, 1], eng: ['E1', 'E2', 'E6'] },
    { id: 397, q: "Many major cities have a problem with homelessness. How can this be solved?", topic: "Homelessness in cities", fam: [0, 2, 1], eng: ['E2', 'E8', 'E7'] },
    { id: 398, q: "Migration of workers from rural to urban areas is increasing. What are the causes and effects of this?", topic: "Rural to urban migration", fam: [2, 8, 1], eng: ['E2', 'E6', 'E7'] }
];
